//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMStudio.Lib.Test.Migrations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MigrationSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MigrationSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMStudio.Lib.Test.Migrations.Resources.MigrationSql", typeof(MigrationSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 0001_ExecuteSql.sql
        ///
        ///--CREATE TABLE Table1
        ///--(
        ///--	Id		INTEGER		PRIMARY KEY ASC,
        ///--	Name	VARCHAR(100)
        ///--)
        ///
        ///--CREATE TABLE Table1
        ///--(
        ///--	Id		INTEGER		PRIMARY KEY ASC,
        ///--	Name	VARCHAR(100)
        ///--)
        ///
        ///--CREATE TABLE Table1
        ///--(
        ///--	Id		INTEGER		PRIMARY KEY ASC,
        ///--	Name	VARCHAR(100)
        ///--)
        ///
        ///--CREATE TABLE Table1
        ///--(
        ///--	Id		INTEGER		PRIMARY KEY ASC,
        ///--	Name	VARCHAR(100)
        ///--)
        ///
        ///--CREATE TABLE Table1
        ///--(
        ///--	Id		INTEGER		PRIMARY KEY ASC,
        ///--	Name	VARCHAR(100)
        ///--)
        ///
        ///--CREATE TABLE Table1
        ///--(
        ///--	Id		INTEGER		PRIMARY KEY ASC,
        ///--	N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0001_ExecuteSql {
            get {
                return ResourceManager.GetString("_0001_ExecuteSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 0002_AddTable.sql.
        /// </summary>
        internal static string _0002_AddTable {
            get {
                return ResourceManager.GetString("_0002_AddTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 0003_AddStoredProcedure.sql.
        /// </summary>
        internal static string _0003_AddStoredProcedure {
            get {
                return ResourceManager.GetString("_0003_AddStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 0004_AlterTable.sql.
        /// </summary>
        internal static string _0004_AlterTable {
            get {
                return ResourceManager.GetString("_0004_AlterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 0005_AlterStoredProcedure.sql.
        /// </summary>
        internal static string _0005_AlterStoredProcedure {
            get {
                return ResourceManager.GetString("_0005_AlterStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 0006_InsertData.sql.
        /// </summary>
        internal static string _0006_InsertData {
            get {
                return ResourceManager.GetString("_0006_InsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Slow migration 1.
        /// </summary>
        internal static string _0008_SlowMigration1 {
            get {
                return ResourceManager.GetString("_0008_SlowMigration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Slow migration 2.
        /// </summary>
        internal static string _0009_SlowMigration2 {
            get {
                return ResourceManager.GetString("_0009_SlowMigration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF XACT_STATE() = 1
        ///BEGIN
        ///	RAISERROR(&apos;This migration cannot be run in a transaction&apos;, 18, 1)
        ///END.
        /// </summary>
        internal static string _0010_NoTransaction {
            get {
                return ResourceManager.GetString("_0010_NoTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF XACT_STATE() = 0
        ///BEGIN
        ///	RAISERROR(&apos;This migration must be run in a transaction&apos;, 18, 1)
        ///END.
        /// </summary>
        internal static string _0011_RequireTransaction {
            get {
                return ResourceManager.GetString("_0011_RequireTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Profile_DEV.sql.
        /// </summary>
        internal static string Profile_DEV {
            get {
                return ResourceManager.GetString("Profile_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Profile_TST.sql.
        /// </summary>
        internal static string Profile_TST {
            get {
                return ResourceManager.GetString("Profile_TST", resourceCulture);
            }
        }
    }
}
